- name: Backup netplan config if it exists
  copy: 
    src: '/etc/netplan/01-netcfg.yaml'
    dest: '/etc/netplan/01-netcfg.old'
    force: no

- name: Create config for netplan
  template:
    src: "files/01-netcfg.yaml.j2"
    dest: "/etc/netplan/01-netcfg.yaml"


